 Ans1
 
 Method 1: Using np.array()

You can directly create a 2D array by passing a list of lists to np.array().

In [192]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
print("Method 1 Output:")
print(arr1)


Method 1 Output:
[[1 2]
 [3 4]]


Method 2: Using np.zeros() and specifying the shape

You can create a 2D array of zeros and then assign the values.

In [193]:
arr2 = np.zeros((2, 2), dtype=int)
arr2[0, 0] = 1
arr2[0, 1] = 2
arr2[1, 0] = 3
arr2[1, 1] = 4
print("\nMethod 2 Output:")
print(arr2)


Method 2 Output:
[[1 2]
 [3 4]]


Method 3: Using np.full() with a specific value

np.full() creates an array of a given shape and fills it with a specified value.

In [194]:
arr3 = np.full((2, 2), 1)
arr3[0, 1] = 2
arr3[1, 0] = 3
arr3[1, 1] = 4
print("\nMethod 3 Output:")
print(arr3)


Method 3 Output:
[[1 2]
 [3 4]]


Ans 2.

In [195]:
import numpy as np

arr = np.linspace(1, 10, 100)

arr_reshaped = arr.reshape(10, 10)

print(arr_reshaped)

[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818]
 [ 8.272

Ans 3.

1. The difference between np.array, np.asarray, and np.asanyarray

These three functions in NumPy are used to create or convert arrays, but they differ in terms of how they handle input data and how they deal with array-like objects.

a. np.array()
Purpose: Creates a new NumPy array from an existing list or array-like object.

Behavior:

.It always returns a new array, regardless of the type of the input.
.It copies the data by default (unless copy=False is specified).
.It can also interpret and convert types, and can be used with different options for data types (dtype), shape (shape), and other properties.

In [196]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


b. np.asarray()
Purpose: Converts the input into a NumPy array, but unlike np.array, it does not copy the data if the input is already a NumPy array.

Behavior:

.If the input is already a NumPy array, np.asarray() returns the same array without making a copy.
.If the input is a list, it creates a new NumPy array.
.It's more efficient when you are working with NumPy arrays and do not need to make a copy.

In [197]:
import numpy as np
arr = np.asarray([1, 2, 3])
print(arr)

[1 2 3]


c. np.asanyarray()
Purpose: Similar to np.asarray(), but it is more flexible in handling input data types.

Behavior:

np.asanyarray() will not convert an input of a subclass of ndarray (e.g., a masked_array or matrix) into a base ndarray. It preserves the input's subclass type.
If the input is not a NumPy array, it behaves similarly to np.asarray(), creating a new array.

In [198]:
import numpy as np
arr = np.asanyarray([1, 2, 3])
print(arr)

[1 2 3]


2. The difference between Deep Copy and Shallow Copy
a. Shallow Copy

.Definition: A shallow copy of an object creates a new object, but does not create copies of nested objects (like lists or arrays inside the object). Instead, the references to the nested objects are copied.

.Behavior: The new object and the original object share references to the same nested objects. If a nested object is modified in one, the change is reflected in the other.

.Method to create: In Python, you can create a shallow copy using methods like .copy() (for lists) or copy.copy() from the copy module.

In [199]:
import copy
a = [1, [2, 3]]
b = copy.copy(a)
b[1][0] = 99
print(a)  # Output: [1, [99, 3]]

[1, [99, 3]]


b. Deep Copy

.Definition: A deep copy creates a new object and recursively copies all nested objects, so the new object is completely independent of the original object.

.Behavior: The original object and the deep-copied object do not share references to any objects. Changes to nested objects in the deep copy will not affect the original object.

.Method to create: In Python, you can create a deep copy using copy.deepcopy() from the copy module.

In [200]:
import copy
a = [1, [2, 3]]
b = copy.deepcopy(a)
b[1][0] = 99
print(a)  # Output: [1, [2, 3]]
print(b)  # Output: [1, [99, 3]]

[1, [2, 3]]
[1, [99, 3]]


Ans 4.

In [201]:
import numpy as np

arr = np.random.uniform(5, 20, (3, 3))

arr_rounded = np.round(arr, 2)

print("Original Array:")
print(arr)
print("\nRounded Array:")
print(arr_rounded)

Original Array:
[[10.70307351  8.17627096 12.31467953]
 [ 6.20293105  7.60562678 10.1493577 ]
 [ 5.56904476 12.16711612 13.76905739]]

Rounded Array:
[[10.7   8.18 12.31]
 [ 6.2   7.61 10.15]
 [ 5.57 12.17 13.77]]


Ans 5.

In [202]:
import numpy as np

arr = np.random.randint(1, 11, (5, 6))

even_numbers = arr[arr % 2 == 0]

odd_numbers = arr[arr % 2 != 0]

print("Original Array:")
print(arr)

print("\nEven Integers:")
print(even_numbers)

print("\nOdd Integers:")
print(odd_numbers)

Original Array:
[[ 1  9  6 10  6  7]
 [ 4  4  2  5  8  3]
 [ 8  4  8  1  2  3]
 [ 7  7  1 10 10  1]
 [ 1  1  1  2  4  6]]

Even Integers:
[ 6 10  6  4  4  2  8  8  4  8  2 10 10  2  4  6]

Odd Integers:
[1 9 7 5 3 1 3 7 7 1 1 1 1 1]


Ans 6.

In [203]:
import numpy as np

arr = np.random.randint(1, 11, (3, 3, 3))

max_indices = np.argmax(arr, axis=2)

arr_multiplied = np.multiply(arr, arr)

print("Original 3D Array:")
print(arr)

print("\nIndices of Maximum Values Along Each Depth Level:")
print(max_indices)

print("\nElement-wise Multiplication of the Array with Itself:")
print(arr_multiplied)


Original 3D Array:
[[[ 4  1  6]
  [ 9  4  1]
  [ 1  7  8]]

 [[ 8  9  2]
  [10  7  3]
  [ 1  8  2]]

 [[ 4  6  4]
  [ 8  1  8]
  [ 1  3  8]]]

Indices of Maximum Values Along Each Depth Level:
[[2 0 2]
 [1 0 1]
 [1 0 2]]

Element-wise Multiplication of the Array with Itself:
[[[ 16   1  36]
  [ 81  16   1]
  [  1  49  64]]

 [[ 64  81   4]
  [100  49   9]
  [  1  64   4]]

 [[ 16  36  16]
  [ 64   1  64]
  [  1   9  64]]]


Ans 7.

In [204]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Phone': ['(123) 456-7890', '987-654-3210', '555.123.4567'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

df['Phone'] = df['Phone'].replace(r'\D', '', regex=True)

df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')  

print("Cleaned DataFrame:")
print(df)

print("\nData Types of Each Column:")
print(df.dtypes)

Cleaned DataFrame:
      Name       Phone  Age
0    Alice  1234567890   25
1      Bob  9876543210   30
2  Charlie  5551234567   35

Data Types of Each Column:
Name     object
Phone     int64
Age       int64
dtype: object


Ans 8.

1. Read the 'data.csv' file while skipping the first 50 rows.

You can use the skiprows parameter in pd.read_csv() to skip the first 50 rows.

2. Only read specific columns ('Last Name', 'Gender', 'Email', 'Phone', 'Salary') from the file.

You can use the usecols parameter to select specific columns to read.

3. Display the first 10 rows of the filtered dataset.

Use .head(10) to display the first 10 rows.

4. Extract the 'Salary' column as a Series and display its last 5 values.

You can extract the column directly and use .tail(5) to display the last 5 values.

Ans 11.

In [205]:
import pandas as pd
import numpy as np

series1 = np.random.randint(10, 51, size=50)

series2 = np.random.randint(100, 1001, size=50)

df = pd.DataFrame({
    'col1': series1,
    'col2': series2
})

print(df.head())

   col1  col2
0    39   266
1    24   991
2    46   553
3    22   954
4    41   737


Ans 2.